basePath: /
consumes:
    - application/json
definitions:
    Texture:
        description: Texture defines the structure for an API texture
        properties:
            id:
                description: Unique id identifying texture in the database
                type: string
                x-go-name: ID
            name:
                description: Texture name for identification by the end-user
                type: string
                x-go-name: Name
            path:
                description: Filepath under which the texture can be found in the filesystem
                type: string
                x-go-name: FilePath
            tags:
                description: Tags roughly describing the texture properties
                items:
                    type: string
                type: array
                x-go-name: Tags
        required:
            - id
            - name
            - path
        type: object
        x-go-package: github.com/KrzysztofSieczkiewicz/ModelViewerBackend/data
info:
    description: '# Documentation for SceneManager API'
    title: of SceneManager API
    version: 0.0.1
paths:
    /textures:
        get:
            description: Returns all available textures based on id
            operationId: getTextures
            responses:
                "200":
                    $ref: '#/responses/getTexturesResponse'
                "500":
                    $ref: '#/responses/internalServerErrorResponse'
        post:
            description: Adds single texture to the database
            operationId: postTexture
            responses:
                "201":
                    $ref: '#/responses/createdResponse'
    /textures/{id}:
        delete:
            description: 'Deletes a texture from the database '
            operationId: deleteTexture
            responses:
                "200":
                    $ref: '#/responses/okResponse'
                "404":
                    $ref: '#/responses/notFoundResponse'
                "500":
                    $ref: '#/responses/internalServerErrorResponse'
        get:
            description: Returns single texture based on id
            operationId: getTexture
            responses:
                "200":
                    $ref: '#/responses/getTextureResponse'
                "404":
                    $ref: '#/responses/notFoundResponse'
                "500":
                    $ref: '#/responses/internalServerErrorResponse'
        put:
            description: Updates single texture based on id
            operationId: putTexture
            responses:
                "201":
                    $ref: '#/responses/createdResponse'
                "404":
                    $ref: '#/responses/notFoundResponse'
                "500":
                    $ref: '#/responses/internalServerErrorResponse'
produces:
    - application/json
responses:
    createdResponse:
        description: ""
    getTextureResponse:
        description: ""
        schema:
            $ref: '#/definitions/Texture'
    getTexturesResponse:
        description: ""
        schema:
            items:
                $ref: '#/definitions/Texture'
            type: array
    internalServerErrorResponse:
        description: ""
    noContentResponse:
        description: ""
    notFoundResponse:
        description: ""
    okResponse:
        description: ""
schemes:
    - http
swagger: "2.0"
